-- =============================================================================
-- FineX adatbázisséma
--
-- A sémát a Flyway kezeli verziózott migrációkkal, a Hibernate csak ellenőrzi
-- (spring.jpa.hibernate.ddl-auto=validate), hogy az entitások megfelelnek-e neki.
-- A pénzügyi táblák idegen kulcsai szándékosan nem kaszkádolnak: könyvelt adat
-- nem törlődhet egy másik rekord törlésének mellékhatásaként.
-- =============================================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    phone         VARCHAR(30),
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email),
    -- kisbetűs tárolás + UNIQUE = kis- és nagybetűre érzéketlen egyediség
    CONSTRAINT ck_users_email_lowercase CHECK (email = lower(email)),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'BLOCKED'))
);

CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL REFERENCES users (id),
    name           VARCHAR(100)  NOT NULL,
    account_number VARCHAR(34)   NOT NULL,
    account_type   VARCHAR(20)   NOT NULL DEFAULT 'CURRENT',
    balance        NUMERIC(18,2) NOT NULL DEFAULT 0,
    currency       VARCHAR(3)    NOT NULL DEFAULT 'HUF',
    status         VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uk_accounts_account_number UNIQUE (account_number),
    -- hitelkeret nincs: a számla nem mehet mínuszba
    CONSTRAINT ck_accounts_balance CHECK (balance >= 0),
    CONSTRAINT ck_accounts_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_accounts_type CHECK (account_type IN ('CURRENT', 'SAVINGS', 'CREDIT')),
    CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'FROZEN', 'CLOSED'))
);

CREATE INDEX idx_accounts_user_id ON accounts (user_id);

CREATE TABLE cards (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id             BIGINT        NOT NULL REFERENCES accounts (id),
    card_number            VARCHAR(19)   NOT NULL,
    holder_name            VARCHAR(100)  NOT NULL,
    expiry_date            DATE          NOT NULL,
    status                 VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    daily_limit            NUMERIC(18,2) NOT NULL,
    online_payment_enabled BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uk_cards_card_number UNIQUE (card_number),
    CONSTRAINT ck_cards_card_number CHECK (card_number ~ '^[0-9]{16}$'),
    CONSTRAINT ck_cards_daily_limit CHECK (daily_limit >= 0),
    CONSTRAINT ck_cards_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'CANCELLED'))
);

CREATE INDEX idx_cards_account_id ON cards (account_id);

-- A tranzakció mindig pozitív összeg, az irányt a típus adja meg
CREATE TABLE transactions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT        NOT NULL REFERENCES accounts (id),
    card_id      BIGINT        REFERENCES cards (id),
    type         VARCHAR(20)   NOT NULL,
    amount       NUMERIC(18,2) NOT NULL,
    currency     VARCHAR(3)    NOT NULL,
    message      VARCHAR(255),
    partner_name VARCHAR(150),
    from_account VARCHAR(34),
    to_account   VARCHAR(34),
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_transactions_amount CHECK (amount > 0),
    CONSTRAINT ck_transactions_type CHECK (type IN ('INCOME', 'OUTCOME', 'TRANSFER_IN', 'TRANSFER_OUT'))
);

-- A leggyakoribb lekérdezés: egy számla tételei időrendben visszafelé
CREATE INDEX idx_transactions_account_created ON transactions (account_id, created_at DESC);
CREATE INDEX idx_transactions_card_id ON transactions (card_id);

CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(20),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE transaction_categories (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES transactions (id) ON DELETE CASCADE,
    category_id    BIGINT NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT uk_transaction_categories UNIQUE (transaction_id, category_id)
);

CREATE INDEX idx_trxcat_category_id ON transaction_categories (category_id);

CREATE TABLE balance_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT        NOT NULL REFERENCES accounts (id),
    balance    NUMERIC(18,2) NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_balance_history_account_created ON balance_history (account_id, created_at);

CREATE TABLE savings_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL REFERENCES users (id),
    name          VARCHAR(100)  NOT NULL,
    balance       NUMERIC(18,2) NOT NULL DEFAULT 0,
    currency      VARCHAR(3)    NOT NULL DEFAULT 'HUF',
    interest_rate NUMERIC(5,2)  NOT NULL DEFAULT 0,
    target_amount NUMERIC(18,2),
    status        VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_savings_balance CHECK (balance >= 0),
    CONSTRAINT ck_savings_interest_rate CHECK (interest_rate BETWEEN 0 AND 100),
    CONSTRAINT ck_savings_target_amount CHECK (target_amount IS NULL OR target_amount > 0),
    CONSTRAINT ck_savings_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE INDEX idx_savings_accounts_user_id ON savings_accounts (user_id);
-- Részleges egyedi index: egy felhasználónak nem lehet két azonos nevű NYITOTT megtakarítása,
-- de egy lezárt "Nyaralás" után nyithat újat ugyanezzel a névvel
CREATE UNIQUE INDEX uk_savings_user_name_open ON savings_accounts (user_id, lower(name)) WHERE status <> 'CLOSED';

CREATE TABLE savings_transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    savings_account_id BIGINT        NOT NULL REFERENCES savings_accounts (id),
    type               VARCHAR(20)   NOT NULL,
    amount             NUMERIC(18,2) NOT NULL,
    balance_after      NUMERIC(18,2) NOT NULL,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_savings_tx_amount CHECK (amount > 0),
    CONSTRAINT ck_savings_tx_balance_after CHECK (balance_after >= 0),
    CONSTRAINT ck_savings_tx_type CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'INTEREST'))
);

CREATE INDEX idx_savings_tx_savings_created ON savings_transactions (savings_account_id, created_at DESC);

CREATE TABLE beneficiaries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name           VARCHAR(150) NOT NULL,
    account_number VARCHAR(34)  NOT NULL,
    note           VARCHAR(255),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_beneficiaries_user_account UNIQUE (user_id, account_number)
);

-- A tulajdonos a forrásszámlán keresztül érhető el (accounts.user_id), ezért nincs külön user_id oszlop
CREATE TABLE standing_orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          BIGINT        NOT NULL REFERENCES accounts (id),
    to_account_number   VARCHAR(34)   NOT NULL,
    partner_name        VARCHAR(150)  NOT NULL,
    amount              NUMERIC(18,2) NOT NULL,
    message             VARCHAR(255),
    frequency           VARCHAR(20)   NOT NULL,
    next_execution_date DATE          NOT NULL,
    active              BOOLEAN       NOT NULL DEFAULT TRUE,
    last_execution_at   TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_standing_orders_amount CHECK (amount > 0),
    CONSTRAINT ck_standing_orders_frequency CHECK (frequency IN ('WEEKLY', 'MONTHLY'))
);

CREATE INDEX idx_standing_orders_account_id ON standing_orders (account_id);
-- Az ütemező csak az aktív, esedékes megbízásokat keresi
CREATE INDEX idx_standing_orders_due ON standing_orders (next_execution_date) WHERE active;

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(20)  NOT NULL,
    title      VARCHAR(150) NOT NULL,
    message    VARCHAR(500) NOT NULL,
    is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_notifications_type CHECK (type IN ('TRANSACTION', 'SECURITY', 'SAVINGS', 'SUPPORT', 'SYSTEM'))
);

CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);
-- Az olvasatlan értesítések számlálója csak ezt a kis indexet használja
CREATE INDEX idx_notifications_unread ON notifications (user_id) WHERE NOT is_read;

CREATE TABLE support_tickets (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    title      VARCHAR(200) NOT NULL,
    message    TEXT         NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_support_tickets_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED'))
);

CREATE INDEX idx_support_tickets_user_id ON support_tickets (user_id);
CREATE INDEX idx_support_tickets_status ON support_tickets (status);

CREATE TABLE support_ticket_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id  BIGINT      NOT NULL REFERENCES support_tickets (id) ON DELETE CASCADE,
    author_id  BIGINT      NOT NULL REFERENCES users (id),
    message    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ticket_messages_ticket_created ON support_ticket_messages (ticket_id, created_at);

-- Ismeretlen e-mail címmel érkező próbálkozás is naplózódik, ezért a user_id lehet üres
CREATE TABLE login_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    email          VARCHAR(255) NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    ip_address     VARCHAR(45),
    user_agent     TEXT,
    failure_reason VARCHAR(255),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_login_logs_status CHECK (status IN ('SUCCESS', 'FAILED'))
);

CREATE INDEX idx_login_logs_user_created ON login_logs (user_id, created_at DESC);
CREATE INDEX idx_login_logs_email_created ON login_logs (email, created_at DESC);
CREATE INDEX idx_login_logs_created_at ON login_logs (created_at);
